// AI-generated from TypeScript source: sake.ts
import 'dart:convert';
import 'package:autocomplete/src/spec.dart';

final List<FigOption> commonOptions = [
  FigOption(
    name: ['--config-path', '-c'],
    description: 'Specify the path to the configuration file',
    args: [
      FigArg(
        name: 'path',
        template: 'filepaths',
      ),
    ],
    isPersistent: true,
  ),
  FigOption(
    name: ['--sake-app-path', '-s'],
    description: 'Specify the path for the SakeApp package',
    args: [
      FigArg(
        name: 'path',
        template: 'folders',
      ),
    ],
    isPersistent: true,
  ),
];

final List<FigOption> commonCommandSpecificOptions = [
  FigOption(
    name: ['--case-converting-strategy'],
    description: "Specify the strategy for converting command names' case",
    args: [
      FigArg(
        name: 'strategy',
        defaultValue: 'keepOriginal',
        suggestions: [
          FigSuggestion(name: 'keepOriginal'),
          FigSuggestion(name: 'toSnakeCase'),
          FigSuggestion(name: 'toKebabCase'),
        ],
      ),
    ],
    priority: 55,
  ),
  FigOption(
    name: ['--sake-app-prebuilt-binary-path', '-b'],
    description: 'Specify the path to the prebuilt SakeApp binary',
    args: [
      FigArg(
        name: 'path',
        template: 'filepaths',
      ),
    ],
    priority: 55,
  ),
];

List<FigSuggestion> _sakeRunPostProcess(String out, [List<String>? tokens]) {
  try {
    final Map<String, dynamic> commands = jsonDecode(out);
    final List<FigSuggestion> suggestions = [];
    final groups = commands['groups'] as Map<String, dynamic>;
    for (final groupName in groups.keys) {
      final group = groups[groupName] as List<dynamic>;
      for (final cmd in group) {
        suggestions.add(FigSuggestion(
          name: cmd['name'],
          description: cmd['description'],
          priority: 76,
          icon: '🍶',
        ));
      }
    }
    return suggestions;
  } catch (e) {
    return [];
  }
}

final FigSpec sakeSpec = FigSpec(
  name: 'sake',
  description:
      '🍶 Swift-based utility for managing project commands, inspired by Make',
  subcommands: [
    FigSubcommand(
      name: 'init',
      description:
          'Initialize a new SakeApp project template for defining commands',
      options: [...commonOptions],
    ),
    FigSubcommand(
      name: 'clean',
      description:
          'Remove all build artifacts generated by the SakeApp to ensure a clean state for future builds',
      options: [...commonOptions],
    ),
    FigSubcommand(
      name: 'edit',
      description: 'Open the SakeApp in Xcode (macOS only)',
      options: [...commonOptions],
    ),
    FigSubcommand(
      name: 'list',
      description: 'List all available commands defined in the SakeApp',
      options: [
        ...commonOptions,
        ...commonCommandSpecificOptions,
        FigOption(
          name: ['--json', '-j'],
          description: 'Output the list of commands in JSON format',
          priority: 45,
        ),
      ],
    ),
    FigSubcommand(
      name: 'build',
      description: 'Manually trigger a rebuild of the SakeApp',
      options: [
        ...commonOptions,
        FigOption(
          name: ['--show-bin-path'],
          description: 'Print the path to the built SakeApp executable',
          priority: 45,
        ),
      ],
    ),
    FigSubcommand(
      name: 'run',
      description: 'Run the specified command from the SakeApp',
      args: [
        FigArg(
          name: 'command',
          description: 'The command to run',
          generators: [
            FigGenerator(
              script: ['sake', 'list', '--json'],
              postProcess: _sakeRunPostProcess,
            ),
          ],
        ),
      ],
      options: [...commonOptions, ...commonCommandSpecificOptions],
    ),
  ],
  options: [
    FigOption(
      name: ['--help', '-h'],
      description: 'Show help information',
      isPersistent: true,
      priority: 40,
    ),
    FigOption(
      name: ['--version'],
      description: 'Show the version',
      priority: 40,
    ),
  ],
);
