// GENERATED by tools/build-handler-index.cjs — do not edit by hand.
// Regenerate after adding/renaming handlers:
//   node tools/build-handler-index.cjs
//
// Each command's dynamic handlers live in a DEFERRED library that is
// loadLibrary()ed only when that command's JSON spec is first loaded,
// so an app pays for handler code only for the commands it completes.

import 'package:autocomplete/src/json_spec.dart';

import 'amplify.dart' deferred as amplify;
import 'ansible_doc.dart' deferred as ansible_doc;
import 'ant.dart' deferred as ant;
import 'apt.dart' deferred as apt;
import 'arch.dart' deferred as arch;
import 'arduino_cli.dart' deferred as arduino_cli;
import 'asdf.dart' deferred as asdf;
import 'assimp.dart' deferred as assimp;
import 'atuin.dart' deferred as atuin;
import 'aws.dart' deferred as aws;
import 'az.dart' deferred as az;
import 'bat.dart' deferred as bat;
import 'bazel.dart' deferred as bazel;
import 'black.dart' deferred as black;
import 'blitz.dart' deferred as blitz;
import 'bosh.dart' deferred as bosh;
import 'brew.dart' deferred as brew;
import 'bun.dart' deferred as bun;
import 'bundle.dart' deferred as bundle;
import 'bunx.dart' deferred as bunx;
import 'capacitor.dart' deferred as capacitor;
import 'cargo.dart' deferred as cargo;
import 'cf.dart' deferred as cf;
import 'checkov.dart' deferred as checkov;
import 'chezmoi.dart' deferred as chezmoi;
import 'chown.dart' deferred as chown;
import 'chsh.dart' deferred as chsh;
import 'cloudwatch.dart' deferred as cloudwatch;
import 'composer.dart' deferred as composer;
import 'conda.dart' deferred as conda;
import 'copilot.dart' deferred as copilot;
import 'cordova.dart' deferred as cordova;
import 'dapr.dart' deferred as dapr;
import 'dcli.dart' deferred as dcli;
import 'dd.dart' deferred as dd;
import 'defaultbrowser.dart' deferred as defaultbrowser;
import 'defaults.dart' deferred as defaults;
import 'degit.dart' deferred as degit;
import 'deployctl.dart' deferred as deployctl;
import 'django_admin.dart' deferred as django_admin;
import 'docker.dart' deferred as docker;
import 'docker_compose.dart' deferred as docker_compose;
import 'doppler.dart' deferred as doppler;
import 'dotnet_dynamic.dart' deferred as dotnet_dynamic;
import 'dotnet_run.dart' deferred as dotnet_run;
import 'dotnet_tool.dart' deferred as dotnet_tool;
import 'drush.dart' deferred as drush;
import 'eb.dart' deferred as eb;
import 'echo.dart' deferred as echo;
import 'ecs.dart' deferred as ecs;
import 'elm.dart' deferred as elm;
import 'elm_json.dart' deferred as elm_json;
import 'env.dart' deferred as env;
import 'envchain.dart' deferred as envchain;
import 'esbuild.dart' deferred as esbuild;
import 'eslint.dart' deferred as eslint;
import 'expressots.dart' deferred as expressots;
import 'ffmpeg.dart' deferred as ffmpeg;
import 'fig.dart' deferred as fig;
import 'fin.dart' deferred as fin;
import 'firebase.dart' deferred as firebase;
import 'firefox.dart' deferred as firefox;
import 'fisher.dart' deferred as fisher;
import 'flyctl.dart' deferred as flyctl;
import 'fnm.dart' deferred as fnm;
import 'fvm.dart' deferred as fvm;
import 'gem.dart' deferred as gem;
import 'gh.dart' deferred as gh;
import 'git.dart' deferred as git;
import 'git_cliff.dart' deferred as git_cliff;
import 'git_flow.dart' deferred as git_flow;
import 'git_profile.dart' deferred as git_profile;
import 'go_task.dart' deferred as go_task;
import 'goto.dart' deferred as goto;
import 'gource.dart' deferred as gource;
import 'gpg.dart' deferred as gpg;
import 'herd.dart' deferred as herd;
import 'heroku.dart' deferred as heroku;
import 'hugo.dart' deferred as hugo;
import 'hyper.dart' deferred as hyper;
import 'iam.dart' deferred as iam;
import 'ibus.dart' deferred as ibus;
import 'iconv.dart' deferred as iconv;
import 'id.dart' deferred as id;
import 'ignite_cli.dart' deferred as ignite_cli;
import 'ipatool.dart' deferred as ipatool;
import 'j.dart' deferred as j;
import 'jenv.dart' deferred as jenv;
import 'just.dart' deferred as just;
import 'k3d.dart' deferred as k3d;
import 'k9s.dart' deferred as k9s;
import 'kamal.dart' deferred as kamal;
import 'keytool.dart' deferred as keytool;
import 'kill.dart' deferred as kill;
import 'killall.dart' deferred as killall;
import 'kind.dart' deferred as kind;
import 'kitty.dart' deferred as kitty;
import 'kool.dart' deferred as kool;
import 'kubectl.dart' deferred as kubectl;
import 'kubectx.dart' deferred as kubectx;
import 'kubens.dart' deferred as kubens;
import 'launchctl.dart' deferred as launchctl;
import 'lerna.dart' deferred as lerna;
import 'limactl.dart' deferred as limactl;
import 'login.dart' deferred as login;
import 'lsof.dart' deferred as lsof;
import 'm.dart' deferred as m;
import 'mackup.dart' deferred as mackup;
import 'magento.dart' deferred as magento;
import 'make.dart' deferred as make;
import 'mamba.dart' deferred as mamba;
import 'man.dart' deferred as man;
import 'mask.dart' deferred as mask;
import 'mdfind.dart' deferred as mdfind;
import 'meteor.dart' deferred as meteor;
import 'mgnl.dart' deferred as mgnl;
import 'mix.dart' deferred as mix;
import 'mkinitcpio.dart' deferred as mkinitcpio;
import 'mount.dart' deferred as mount;
import 'n.dart' deferred as n;
import 'network_quality.dart' deferred as network_quality;
import 'networksetup.dart' deferred as networksetup;
import 'nextflow.dart' deferred as nextflow;
import 'ng.dart' deferred as ng;
import 'node.dart' deferred as node;
import 'npm.dart' deferred as npm;
import 'npx.dart' deferred as npx;
import 'ns.dart' deferred as ns;
import 'nuxi.dart' deferred as nuxi;
import 'nx.dart' deferred as nx;
import 'okteto.dart' deferred as okteto;
import 'ollama.dart' deferred as ollama;
import 'op.dart' deferred as op;
import 'oxlint.dart' deferred as oxlint;
import 'pass.dart' deferred as pass;
import 'passwd.dart' deferred as passwd;
import 'php.dart' deferred as php;
import 'php_artisan.dart' deferred as php_artisan;
import 'php_bin_console.dart' deferred as php_bin_console;
import 'php_please.dart' deferred as php_please;
import 'phpunit_watcher.dart' deferred as phpunit_watcher;
import 'pip.dart' deferred as pip;
import 'pipx.dart' deferred as pipx;
import 'pnpm.dart' deferred as pnpm;
import 'podman.dart' deferred as podman;
import 'pre_commit.dart' deferred as pre_commit;
import 'projj.dart' deferred as projj;
import 'pulumi.dart' deferred as pulumi;
import 'pyenv.dart' deferred as pyenv;
import 'python.dart' deferred as python;
import 'python3.dart' deferred as python3;
import 'q.dart' deferred as q;
import 'quickmail.dart' deferred as quickmail;
import 'rails.dart' deferred as rails;
import 'rake.dart' deferred as rake;
import 'rancher.dart' deferred as rancher;
import 'rclone.dart' deferred as rclone;
import 'react_native.dart' deferred as react_native;
import 'redwood.dart' deferred as redwood;
import 'rich.dart' deferred as rich;
import 'robot.dart' deferred as robot;
import 'rsync.dart' deferred as rsync;
import 'rubocop.dart' deferred as rubocop;
import 'ruff.dart' deferred as ruff;
import 'rugby.dart' deferred as rugby;
import 'rush.dart' deferred as rush;
import 'rustup.dart' deferred as rustup;
import 's3api.dart' deferred as s3api;
import 'sake.dart' deferred as sake;
import 'scarb.dart' deferred as scarb;
import 'scc.dart' deferred as scc;
import 'secretsmanager.dart' deferred as secretsmanager;
import 'sequelize.dart' deferred as sequelize;
import 'serverless.dart' deferred as serverless;
import 'shadcn_ui.dart' deferred as shadcn_ui;
import 'shortcuts.dart' deferred as shortcuts;
import 'snaplet.dart' deferred as snaplet;
import 'softwareupdate.dart' deferred as softwareupdate;
import 'spring.dart' deferred as spring;
import 'ssh.dart' deferred as ssh;
import 'ssh_keygen.dart' deferred as ssh_keygen;
import 'stepzen.dart' deferred as stepzen;
import 'sysctl.dart' deferred as sysctl;
import 'systemctl.dart' deferred as systemctl;
import 'task.dart' deferred as task;
import 'taskwarrior.dart' deferred as taskwarrior;
import 'terraform.dart' deferred as terraform;
import 'terragrunt.dart' deferred as terragrunt;
import 'tfsec.dart' deferred as tfsec;
import 'tldr.dart' deferred as tldr;
import 'tmuxinator.dart' deferred as tmuxinator;
import 'trex.dart' deferred as trex;
import 'trivy.dart' deferred as trivy;
import 'ts_node.dart' deferred as ts_node;
import 'tsh.dart' deferred as tsh;
import 'turbo.dart' deferred as turbo;
import 'unset.dart' deferred as unset;
import 'v.dart' deferred as v;
import 'valet.dart' deferred as valet;
import 'vite.dart' deferred as vite;
import 'vr.dart' deferred as vr;
import 'vultr_cli.dart' deferred as vultr_cli;
import 'watson.dart' deferred as watson;
import 'wd.dart' deferred as wd;
import 'which.dart' deferred as which;
import 'wifi_password.dart' deferred as wifi_password;
import 'xc.dart' deferred as xc;
import 'xcodeproj.dart' deferred as xcodeproj;
import 'xcodes.dart' deferred as xcodes;
import 'yalc.dart' deferred as yalc;
import 'yarn.dart' deferred as yarn;
import 'ykman.dart' deferred as ykman;
import 'yo.dart' deferred as yo;
import 'youtube_dl.dart' deferred as youtube_dl;
import 'z.dart' deferred as z;
import 'zellij.dart' deferred as zellij;

Future<void> _regAmplify(
    JsonHandlerRegistry r) async {
  await amplify.loadLibrary();
  amplify.registerAmplifyHandlers(r);
}
Future<void> _regAnsible_doc(
    JsonHandlerRegistry r) async {
  await ansible_doc.loadLibrary();
  ansible_doc.registerAnsibleDocHandlers(r);
}
Future<void> _regAnt(
    JsonHandlerRegistry r) async {
  await ant.loadLibrary();
  ant.registerAntHandlers(r);
}
Future<void> _regApt(
    JsonHandlerRegistry r) async {
  await apt.loadLibrary();
  apt.registerAptHandlers(r);
}
Future<void> _regArch(
    JsonHandlerRegistry r) async {
  await arch.loadLibrary();
  arch.registerArchHandlers(r);
}
Future<void> _regArduino_cli(
    JsonHandlerRegistry r) async {
  await arduino_cli.loadLibrary();
  arduino_cli.registerArduinoCliHandlers(r);
}
Future<void> _regAsdf(
    JsonHandlerRegistry r) async {
  await asdf.loadLibrary();
  asdf.registerAsdfHandlers(r);
}
Future<void> _regAssimp(
    JsonHandlerRegistry r) async {
  await assimp.loadLibrary();
  assimp.registerAssimpHandlers(r);
}
Future<void> _regAtuin(
    JsonHandlerRegistry r) async {
  await atuin.loadLibrary();
  atuin.registerAtuinHandlers(r);
}
Future<void> _regAws(
    JsonHandlerRegistry r) async {
  await aws.loadLibrary();
  aws.registerAwsHandlers(r);
}
Future<void> _regAz(
    JsonHandlerRegistry r) async {
  await az.loadLibrary();
  az.registerAzHandlers(r);
}
Future<void> _regBat(
    JsonHandlerRegistry r) async {
  await bat.loadLibrary();
  bat.registerBatHandlers(r);
}
Future<void> _regBazel(
    JsonHandlerRegistry r) async {
  await bazel.loadLibrary();
  bazel.registerBazelHandlers(r);
}
Future<void> _regBlack(
    JsonHandlerRegistry r) async {
  await black.loadLibrary();
  black.registerBlackHandlers(r);
}
Future<void> _regBlitz(
    JsonHandlerRegistry r) async {
  await blitz.loadLibrary();
  blitz.registerBlitzHandlers(r);
}
Future<void> _regBosh(
    JsonHandlerRegistry r) async {
  await bosh.loadLibrary();
  bosh.registerBoshHandlers(r);
}
Future<void> _regBrew(
    JsonHandlerRegistry r) async {
  await brew.loadLibrary();
  brew.registerBrewHandlers(r);
}
Future<void> _regBun(
    JsonHandlerRegistry r) async {
  await bun.loadLibrary();
  bun.registerBunHandlers(r);
}
Future<void> _regBundle(
    JsonHandlerRegistry r) async {
  await bundle.loadLibrary();
  bundle.registerBundleHandlers(r);
}
Future<void> _regBunx(
    JsonHandlerRegistry r) async {
  await bunx.loadLibrary();
  bunx.registerBunxHandlers(r);
}
Future<void> _regCapacitor(
    JsonHandlerRegistry r) async {
  await capacitor.loadLibrary();
  capacitor.registerCapacitorHandlers(r);
}
Future<void> _regCargo(
    JsonHandlerRegistry r) async {
  await cargo.loadLibrary();
  cargo.registerCargoHandlers(r);
}
Future<void> _regCf(
    JsonHandlerRegistry r) async {
  await cf.loadLibrary();
  cf.registerCfHandlers(r);
}
Future<void> _regCheckov(
    JsonHandlerRegistry r) async {
  await checkov.loadLibrary();
  checkov.registerCheckovHandlers(r);
}
Future<void> _regChezmoi(
    JsonHandlerRegistry r) async {
  await chezmoi.loadLibrary();
  chezmoi.registerChezmoiHandlers(r);
}
Future<void> _regChown(
    JsonHandlerRegistry r) async {
  await chown.loadLibrary();
  chown.registerChownHandlers(r);
}
Future<void> _regChsh(
    JsonHandlerRegistry r) async {
  await chsh.loadLibrary();
  chsh.registerChshHandlers(r);
}
Future<void> _regCloudwatch(
    JsonHandlerRegistry r) async {
  await cloudwatch.loadLibrary();
  cloudwatch.registerCloudwatchHandlers(r);
}
Future<void> _regComposer(
    JsonHandlerRegistry r) async {
  await composer.loadLibrary();
  composer.registerComposerHandlers(r);
}
Future<void> _regConda(
    JsonHandlerRegistry r) async {
  await conda.loadLibrary();
  conda.registerCondaHandlers(r);
}
Future<void> _regCopilot(
    JsonHandlerRegistry r) async {
  await copilot.loadLibrary();
  copilot.registerCopilotHandlers(r);
}
Future<void> _regCordova(
    JsonHandlerRegistry r) async {
  await cordova.loadLibrary();
  cordova.registerCordovaHandlers(r);
}
Future<void> _regDapr(
    JsonHandlerRegistry r) async {
  await dapr.loadLibrary();
  dapr.registerDaprHandlers(r);
}
Future<void> _regDcli(
    JsonHandlerRegistry r) async {
  await dcli.loadLibrary();
  dcli.registerDcliHandlers(r);
}
Future<void> _regDd(
    JsonHandlerRegistry r) async {
  await dd.loadLibrary();
  dd.registerDdHandlers(r);
}
Future<void> _regDefaultbrowser(
    JsonHandlerRegistry r) async {
  await defaultbrowser.loadLibrary();
  defaultbrowser.registerDefaultbrowserHandlers(r);
}
Future<void> _regDefaults(
    JsonHandlerRegistry r) async {
  await defaults.loadLibrary();
  defaults.registerDefaultsHandlers(r);
}
Future<void> _regDegit(
    JsonHandlerRegistry r) async {
  await degit.loadLibrary();
  degit.registerDegitHandlers(r);
}
Future<void> _regDeployctl(
    JsonHandlerRegistry r) async {
  await deployctl.loadLibrary();
  deployctl.registerDeployctlHandlers(r);
}
Future<void> _regDjango_admin(
    JsonHandlerRegistry r) async {
  await django_admin.loadLibrary();
  django_admin.registerDjangoAdminHandlers(r);
}
Future<void> _regDocker(
    JsonHandlerRegistry r) async {
  await docker.loadLibrary();
  docker.registerDockerHandlers(r);
}
Future<void> _regDocker_compose(
    JsonHandlerRegistry r) async {
  await docker_compose.loadLibrary();
  docker_compose.registerDockerComposeHandlers(r);
}
Future<void> _regDoppler(
    JsonHandlerRegistry r) async {
  await doppler.loadLibrary();
  doppler.registerDopplerHandlers(r);
}
Future<void> _regDotnet_dynamic(
    JsonHandlerRegistry r) async {
  await dotnet_dynamic.loadLibrary();
  dotnet_dynamic.registerDotnetDynamicHandlers(r);
}
Future<void> _regDotnet_run(
    JsonHandlerRegistry r) async {
  await dotnet_run.loadLibrary();
  dotnet_run.registerDotnetRunHandlers(r);
}
Future<void> _regDotnet_tool(
    JsonHandlerRegistry r) async {
  await dotnet_tool.loadLibrary();
  dotnet_tool.registerDotnetToolHandlers(r);
}
Future<void> _regDrush(
    JsonHandlerRegistry r) async {
  await drush.loadLibrary();
  drush.registerDrushHandlers(r);
}
Future<void> _regEb(
    JsonHandlerRegistry r) async {
  await eb.loadLibrary();
  eb.registerEbHandlers(r);
}
Future<void> _regEcho(
    JsonHandlerRegistry r) async {
  await echo.loadLibrary();
  echo.registerEchoHandlers(r);
}
Future<void> _regEcs(
    JsonHandlerRegistry r) async {
  await ecs.loadLibrary();
  ecs.registerEcsHandlers(r);
}
Future<void> _regElm(
    JsonHandlerRegistry r) async {
  await elm.loadLibrary();
  elm.registerElmHandlers(r);
}
Future<void> _regElm_json(
    JsonHandlerRegistry r) async {
  await elm_json.loadLibrary();
  elm_json.registerElmJsonHandlers(r);
}
Future<void> _regEnv(
    JsonHandlerRegistry r) async {
  await env.loadLibrary();
  env.registerEnvHandlers(r);
}
Future<void> _regEnvchain(
    JsonHandlerRegistry r) async {
  await envchain.loadLibrary();
  envchain.registerEnvchainHandlers(r);
}
Future<void> _regEsbuild(
    JsonHandlerRegistry r) async {
  await esbuild.loadLibrary();
  esbuild.registerEsbuildHandlers(r);
}
Future<void> _regEslint(
    JsonHandlerRegistry r) async {
  await eslint.loadLibrary();
  eslint.registerEslintHandlers(r);
}
Future<void> _regExpressots(
    JsonHandlerRegistry r) async {
  await expressots.loadLibrary();
  expressots.registerExpressotsHandlers(r);
}
Future<void> _regFfmpeg(
    JsonHandlerRegistry r) async {
  await ffmpeg.loadLibrary();
  ffmpeg.registerFfmpegHandlers(r);
}
Future<void> _regFig(
    JsonHandlerRegistry r) async {
  await fig.loadLibrary();
  fig.registerFigHandlers(r);
}
Future<void> _regFin(
    JsonHandlerRegistry r) async {
  await fin.loadLibrary();
  fin.registerFinHandlers(r);
}
Future<void> _regFirebase(
    JsonHandlerRegistry r) async {
  await firebase.loadLibrary();
  firebase.registerFirebaseHandlers(r);
}
Future<void> _regFirefox(
    JsonHandlerRegistry r) async {
  await firefox.loadLibrary();
  firefox.registerFirefoxHandlers(r);
}
Future<void> _regFisher(
    JsonHandlerRegistry r) async {
  await fisher.loadLibrary();
  fisher.registerFisherHandlers(r);
}
Future<void> _regFlyctl(
    JsonHandlerRegistry r) async {
  await flyctl.loadLibrary();
  flyctl.registerFlyctlHandlers(r);
}
Future<void> _regFnm(
    JsonHandlerRegistry r) async {
  await fnm.loadLibrary();
  fnm.registerFnmHandlers(r);
}
Future<void> _regFvm(
    JsonHandlerRegistry r) async {
  await fvm.loadLibrary();
  fvm.registerFvmHandlers(r);
}
Future<void> _regGem(
    JsonHandlerRegistry r) async {
  await gem.loadLibrary();
  gem.registerGemHandlers(r);
}
Future<void> _regGh(
    JsonHandlerRegistry r) async {
  await gh.loadLibrary();
  gh.registerGhHandlers(r);
}
Future<void> _regGit(
    JsonHandlerRegistry r) async {
  await git.loadLibrary();
  git.registerGitHandlers(r);
}
Future<void> _regGit_cliff(
    JsonHandlerRegistry r) async {
  await git_cliff.loadLibrary();
  git_cliff.registerGitCliffHandlers(r);
}
Future<void> _regGit_flow(
    JsonHandlerRegistry r) async {
  await git_flow.loadLibrary();
  git_flow.registerGitFlowHandlers(r);
}
Future<void> _regGit_profile(
    JsonHandlerRegistry r) async {
  await git_profile.loadLibrary();
  git_profile.registerGitProfileHandlers(r);
}
Future<void> _regGo_task(
    JsonHandlerRegistry r) async {
  await go_task.loadLibrary();
  go_task.registerGoTaskHandlers(r);
}
Future<void> _regGoto(
    JsonHandlerRegistry r) async {
  await goto.loadLibrary();
  goto.registerGotoHandlers(r);
}
Future<void> _regGource(
    JsonHandlerRegistry r) async {
  await gource.loadLibrary();
  gource.registerGourceHandlers(r);
}
Future<void> _regGpg(
    JsonHandlerRegistry r) async {
  await gpg.loadLibrary();
  gpg.registerGpgHandlers(r);
}
Future<void> _regHerd(
    JsonHandlerRegistry r) async {
  await herd.loadLibrary();
  herd.registerHerdHandlers(r);
}
Future<void> _regHeroku(
    JsonHandlerRegistry r) async {
  await heroku.loadLibrary();
  heroku.registerHerokuHandlers(r);
}
Future<void> _regHugo(
    JsonHandlerRegistry r) async {
  await hugo.loadLibrary();
  hugo.registerHugoHandlers(r);
}
Future<void> _regHyper(
    JsonHandlerRegistry r) async {
  await hyper.loadLibrary();
  hyper.registerHyperHandlers(r);
}
Future<void> _regIam(
    JsonHandlerRegistry r) async {
  await iam.loadLibrary();
  iam.registerIamHandlers(r);
}
Future<void> _regIbus(
    JsonHandlerRegistry r) async {
  await ibus.loadLibrary();
  ibus.registerIbusHandlers(r);
}
Future<void> _regIconv(
    JsonHandlerRegistry r) async {
  await iconv.loadLibrary();
  iconv.registerIconvHandlers(r);
}
Future<void> _regId(
    JsonHandlerRegistry r) async {
  await id.loadLibrary();
  id.registerIdHandlers(r);
}
Future<void> _regIgnite_cli(
    JsonHandlerRegistry r) async {
  await ignite_cli.loadLibrary();
  ignite_cli.registerIgniteCliHandlers(r);
}
Future<void> _regIpatool(
    JsonHandlerRegistry r) async {
  await ipatool.loadLibrary();
  ipatool.registerIpatoolHandlers(r);
}
Future<void> _regJ(
    JsonHandlerRegistry r) async {
  await j.loadLibrary();
  j.registerJHandlers(r);
}
Future<void> _regJenv(
    JsonHandlerRegistry r) async {
  await jenv.loadLibrary();
  jenv.registerJenvHandlers(r);
}
Future<void> _regJust(
    JsonHandlerRegistry r) async {
  await just.loadLibrary();
  just.registerJustHandlers(r);
}
Future<void> _regK3d(
    JsonHandlerRegistry r) async {
  await k3d.loadLibrary();
  k3d.registerK3dHandlers(r);
}
Future<void> _regK9s(
    JsonHandlerRegistry r) async {
  await k9s.loadLibrary();
  k9s.registerK9sHandlers(r);
}
Future<void> _regKamal(
    JsonHandlerRegistry r) async {
  await kamal.loadLibrary();
  kamal.registerKamalHandlers(r);
}
Future<void> _regKeytool(
    JsonHandlerRegistry r) async {
  await keytool.loadLibrary();
  keytool.registerKeytoolHandlers(r);
}
Future<void> _regKill(
    JsonHandlerRegistry r) async {
  await kill.loadLibrary();
  kill.registerKillHandlers(r);
}
Future<void> _regKillall(
    JsonHandlerRegistry r) async {
  await killall.loadLibrary();
  killall.registerKillallHandlers(r);
}
Future<void> _regKind(
    JsonHandlerRegistry r) async {
  await kind.loadLibrary();
  kind.registerKindHandlers(r);
}
Future<void> _regKitty(
    JsonHandlerRegistry r) async {
  await kitty.loadLibrary();
  kitty.registerKittyHandlers(r);
}
Future<void> _regKool(
    JsonHandlerRegistry r) async {
  await kool.loadLibrary();
  kool.registerKoolHandlers(r);
}
Future<void> _regKubectl(
    JsonHandlerRegistry r) async {
  await kubectl.loadLibrary();
  kubectl.registerKubectlHandlers(r);
}
Future<void> _regKubectx(
    JsonHandlerRegistry r) async {
  await kubectx.loadLibrary();
  kubectx.registerKubectxHandlers(r);
}
Future<void> _regKubens(
    JsonHandlerRegistry r) async {
  await kubens.loadLibrary();
  kubens.registerKubensHandlers(r);
}
Future<void> _regLaunchctl(
    JsonHandlerRegistry r) async {
  await launchctl.loadLibrary();
  launchctl.registerLaunchctlHandlers(r);
}
Future<void> _regLerna(
    JsonHandlerRegistry r) async {
  await lerna.loadLibrary();
  lerna.registerLernaHandlers(r);
}
Future<void> _regLimactl(
    JsonHandlerRegistry r) async {
  await limactl.loadLibrary();
  limactl.registerLimactlHandlers(r);
}
Future<void> _regLogin(
    JsonHandlerRegistry r) async {
  await login.loadLibrary();
  login.registerLoginHandlers(r);
}
Future<void> _regLsof(
    JsonHandlerRegistry r) async {
  await lsof.loadLibrary();
  lsof.registerLsofHandlers(r);
}
Future<void> _regM(
    JsonHandlerRegistry r) async {
  await m.loadLibrary();
  m.registerMHandlers(r);
}
Future<void> _regMackup(
    JsonHandlerRegistry r) async {
  await mackup.loadLibrary();
  mackup.registerMackupHandlers(r);
}
Future<void> _regMagento(
    JsonHandlerRegistry r) async {
  await magento.loadLibrary();
  magento.registerMagentoHandlers(r);
}
Future<void> _regMake(
    JsonHandlerRegistry r) async {
  await make.loadLibrary();
  make.registerMakeHandlers(r);
}
Future<void> _regMamba(
    JsonHandlerRegistry r) async {
  await mamba.loadLibrary();
  mamba.registerMambaHandlers(r);
}
Future<void> _regMan(
    JsonHandlerRegistry r) async {
  await man.loadLibrary();
  man.registerManHandlers(r);
}
Future<void> _regMask(
    JsonHandlerRegistry r) async {
  await mask.loadLibrary();
  mask.registerMaskHandlers(r);
}
Future<void> _regMdfind(
    JsonHandlerRegistry r) async {
  await mdfind.loadLibrary();
  mdfind.registerMdfindHandlers(r);
}
Future<void> _regMeteor(
    JsonHandlerRegistry r) async {
  await meteor.loadLibrary();
  meteor.registerMeteorHandlers(r);
}
Future<void> _regMgnl(
    JsonHandlerRegistry r) async {
  await mgnl.loadLibrary();
  mgnl.registerMgnlHandlers(r);
}
Future<void> _regMix(
    JsonHandlerRegistry r) async {
  await mix.loadLibrary();
  mix.registerMixHandlers(r);
}
Future<void> _regMkinitcpio(
    JsonHandlerRegistry r) async {
  await mkinitcpio.loadLibrary();
  mkinitcpio.registerMkinitcpioHandlers(r);
}
Future<void> _regMount(
    JsonHandlerRegistry r) async {
  await mount.loadLibrary();
  mount.registerMountHandlers(r);
}
Future<void> _regN(
    JsonHandlerRegistry r) async {
  await n.loadLibrary();
  n.registerNHandlers(r);
}
Future<void> _regNetwork_quality(
    JsonHandlerRegistry r) async {
  await network_quality.loadLibrary();
  network_quality.registerNetworkQualityHandlers(r);
}
Future<void> _regNetworksetup(
    JsonHandlerRegistry r) async {
  await networksetup.loadLibrary();
  networksetup.registerNetworksetupHandlers(r);
}
Future<void> _regNextflow(
    JsonHandlerRegistry r) async {
  await nextflow.loadLibrary();
  nextflow.registerNextflowHandlers(r);
}
Future<void> _regNg(
    JsonHandlerRegistry r) async {
  await ng.loadLibrary();
  ng.registerNgHandlers(r);
}
Future<void> _regNode(
    JsonHandlerRegistry r) async {
  await node.loadLibrary();
  node.registerNodeHandlers(r);
}
Future<void> _regNpm(
    JsonHandlerRegistry r) async {
  await npm.loadLibrary();
  npm.registerNpmHandlers(r);
}
Future<void> _regNpx(
    JsonHandlerRegistry r) async {
  await npx.loadLibrary();
  npx.registerNpxHandlers(r);
}
Future<void> _regNs(
    JsonHandlerRegistry r) async {
  await ns.loadLibrary();
  ns.registerNsHandlers(r);
}
Future<void> _regNuxi(
    JsonHandlerRegistry r) async {
  await nuxi.loadLibrary();
  nuxi.registerNuxiHandlers(r);
}
Future<void> _regNx(
    JsonHandlerRegistry r) async {
  await nx.loadLibrary();
  nx.registerNxHandlers(r);
}
Future<void> _regOkteto(
    JsonHandlerRegistry r) async {
  await okteto.loadLibrary();
  okteto.registerOktetoHandlers(r);
}
Future<void> _regOllama(
    JsonHandlerRegistry r) async {
  await ollama.loadLibrary();
  ollama.registerOllamaHandlers(r);
}
Future<void> _regOp(
    JsonHandlerRegistry r) async {
  await op.loadLibrary();
  op.registerOpHandlers(r);
}
Future<void> _regOxlint(
    JsonHandlerRegistry r) async {
  await oxlint.loadLibrary();
  oxlint.registerOxlintHandlers(r);
}
Future<void> _regPass(
    JsonHandlerRegistry r) async {
  await pass.loadLibrary();
  pass.registerPassHandlers(r);
}
Future<void> _regPasswd(
    JsonHandlerRegistry r) async {
  await passwd.loadLibrary();
  passwd.registerPasswdHandlers(r);
}
Future<void> _regPhp(
    JsonHandlerRegistry r) async {
  await php.loadLibrary();
  php.registerPhpHandlers(r);
}
Future<void> _regPhp_artisan(
    JsonHandlerRegistry r) async {
  await php_artisan.loadLibrary();
  php_artisan.registerPhpArtisanHandlers(r);
}
Future<void> _regPhp_bin_console(
    JsonHandlerRegistry r) async {
  await php_bin_console.loadLibrary();
  php_bin_console.registerPhpBinConsoleHandlers(r);
}
Future<void> _regPhp_please(
    JsonHandlerRegistry r) async {
  await php_please.loadLibrary();
  php_please.registerPhpPleaseHandlers(r);
}
Future<void> _regPhpunit_watcher(
    JsonHandlerRegistry r) async {
  await phpunit_watcher.loadLibrary();
  phpunit_watcher.registerPhpunitWatcherHandlers(r);
}
Future<void> _regPip(
    JsonHandlerRegistry r) async {
  await pip.loadLibrary();
  pip.registerPipHandlers(r);
}
Future<void> _regPipx(
    JsonHandlerRegistry r) async {
  await pipx.loadLibrary();
  pipx.registerPipxHandlers(r);
}
Future<void> _regPnpm(
    JsonHandlerRegistry r) async {
  await pnpm.loadLibrary();
  pnpm.registerPnpmHandlers(r);
}
Future<void> _regPodman(
    JsonHandlerRegistry r) async {
  await podman.loadLibrary();
  podman.registerPodmanHandlers(r);
}
Future<void> _regPre_commit(
    JsonHandlerRegistry r) async {
  await pre_commit.loadLibrary();
  pre_commit.registerPreCommitHandlers(r);
}
Future<void> _regProjj(
    JsonHandlerRegistry r) async {
  await projj.loadLibrary();
  projj.registerProjjHandlers(r);
}
Future<void> _regPulumi(
    JsonHandlerRegistry r) async {
  await pulumi.loadLibrary();
  pulumi.registerPulumiHandlers(r);
}
Future<void> _regPyenv(
    JsonHandlerRegistry r) async {
  await pyenv.loadLibrary();
  pyenv.registerPyenvHandlers(r);
}
Future<void> _regPython(
    JsonHandlerRegistry r) async {
  await python.loadLibrary();
  python.registerPythonHandlers(r);
}
Future<void> _regPython3(
    JsonHandlerRegistry r) async {
  await python3.loadLibrary();
  python3.registerPython3Handlers(r);
}
Future<void> _regQ(
    JsonHandlerRegistry r) async {
  await q.loadLibrary();
  q.registerQHandlers(r);
}
Future<void> _regQuickmail(
    JsonHandlerRegistry r) async {
  await quickmail.loadLibrary();
  quickmail.registerQuickmailHandlers(r);
}
Future<void> _regRails(
    JsonHandlerRegistry r) async {
  await rails.loadLibrary();
  rails.registerRailsHandlers(r);
}
Future<void> _regRake(
    JsonHandlerRegistry r) async {
  await rake.loadLibrary();
  rake.registerRakeHandlers(r);
}
Future<void> _regRancher(
    JsonHandlerRegistry r) async {
  await rancher.loadLibrary();
  rancher.registerRancherHandlers(r);
}
Future<void> _regRclone(
    JsonHandlerRegistry r) async {
  await rclone.loadLibrary();
  rclone.registerRcloneHandlers(r);
}
Future<void> _regReact_native(
    JsonHandlerRegistry r) async {
  await react_native.loadLibrary();
  react_native.registerReactNativeHandlers(r);
}
Future<void> _regRedwood(
    JsonHandlerRegistry r) async {
  await redwood.loadLibrary();
  redwood.registerRedwoodHandlers(r);
}
Future<void> _regRich(
    JsonHandlerRegistry r) async {
  await rich.loadLibrary();
  rich.registerRichHandlers(r);
}
Future<void> _regRobot(
    JsonHandlerRegistry r) async {
  await robot.loadLibrary();
  robot.registerRobotHandlers(r);
}
Future<void> _regRsync(
    JsonHandlerRegistry r) async {
  await rsync.loadLibrary();
  rsync.registerRsyncHandlers(r);
}
Future<void> _regRubocop(
    JsonHandlerRegistry r) async {
  await rubocop.loadLibrary();
  rubocop.registerRubocopHandlers(r);
}
Future<void> _regRuff(
    JsonHandlerRegistry r) async {
  await ruff.loadLibrary();
  ruff.registerRuffHandlers(r);
}
Future<void> _regRugby(
    JsonHandlerRegistry r) async {
  await rugby.loadLibrary();
  rugby.registerRugbyHandlers(r);
}
Future<void> _regRush(
    JsonHandlerRegistry r) async {
  await rush.loadLibrary();
  rush.registerRushHandlers(r);
}
Future<void> _regRustup(
    JsonHandlerRegistry r) async {
  await rustup.loadLibrary();
  rustup.registerRustupHandlers(r);
}
Future<void> _regS3api(
    JsonHandlerRegistry r) async {
  await s3api.loadLibrary();
  s3api.registerS3apiHandlers(r);
}
Future<void> _regSake(
    JsonHandlerRegistry r) async {
  await sake.loadLibrary();
  sake.registerSakeHandlers(r);
}
Future<void> _regScarb(
    JsonHandlerRegistry r) async {
  await scarb.loadLibrary();
  scarb.registerScarbHandlers(r);
}
Future<void> _regScc(
    JsonHandlerRegistry r) async {
  await scc.loadLibrary();
  scc.registerSccHandlers(r);
}
Future<void> _regSecretsmanager(
    JsonHandlerRegistry r) async {
  await secretsmanager.loadLibrary();
  secretsmanager.registerSecretsmanagerHandlers(r);
}
Future<void> _regSequelize(
    JsonHandlerRegistry r) async {
  await sequelize.loadLibrary();
  sequelize.registerSequelizeHandlers(r);
}
Future<void> _regServerless(
    JsonHandlerRegistry r) async {
  await serverless.loadLibrary();
  serverless.registerServerlessHandlers(r);
}
Future<void> _regShadcn_ui(
    JsonHandlerRegistry r) async {
  await shadcn_ui.loadLibrary();
  shadcn_ui.registerShadcnUiHandlers(r);
}
Future<void> _regShortcuts(
    JsonHandlerRegistry r) async {
  await shortcuts.loadLibrary();
  shortcuts.registerShortcutsHandlers(r);
}
Future<void> _regSnaplet(
    JsonHandlerRegistry r) async {
  await snaplet.loadLibrary();
  snaplet.registerSnapletHandlers(r);
}
Future<void> _regSoftwareupdate(
    JsonHandlerRegistry r) async {
  await softwareupdate.loadLibrary();
  softwareupdate.registerSoftwareupdateHandlers(r);
}
Future<void> _regSpring(
    JsonHandlerRegistry r) async {
  await spring.loadLibrary();
  spring.registerSpringHandlers(r);
}
Future<void> _regSsh(
    JsonHandlerRegistry r) async {
  await ssh.loadLibrary();
  ssh.registerSshHandlers(r);
}
Future<void> _regSsh_keygen(
    JsonHandlerRegistry r) async {
  await ssh_keygen.loadLibrary();
  ssh_keygen.registerSshKeygenHandlers(r);
}
Future<void> _regStepzen(
    JsonHandlerRegistry r) async {
  await stepzen.loadLibrary();
  stepzen.registerStepzenHandlers(r);
}
Future<void> _regSysctl(
    JsonHandlerRegistry r) async {
  await sysctl.loadLibrary();
  sysctl.registerSysctlHandlers(r);
}
Future<void> _regSystemctl(
    JsonHandlerRegistry r) async {
  await systemctl.loadLibrary();
  systemctl.registerSystemctlHandlers(r);
}
Future<void> _regTask(
    JsonHandlerRegistry r) async {
  await task.loadLibrary();
  task.registerTaskHandlers(r);
}
Future<void> _regTaskwarrior(
    JsonHandlerRegistry r) async {
  await taskwarrior.loadLibrary();
  taskwarrior.registerTaskwarriorHandlers(r);
}
Future<void> _regTerraform(
    JsonHandlerRegistry r) async {
  await terraform.loadLibrary();
  terraform.registerTerraformHandlers(r);
}
Future<void> _regTerragrunt(
    JsonHandlerRegistry r) async {
  await terragrunt.loadLibrary();
  terragrunt.registerTerragruntHandlers(r);
}
Future<void> _regTfsec(
    JsonHandlerRegistry r) async {
  await tfsec.loadLibrary();
  tfsec.registerTfsecHandlers(r);
}
Future<void> _regTldr(
    JsonHandlerRegistry r) async {
  await tldr.loadLibrary();
  tldr.registerTldrHandlers(r);
}
Future<void> _regTmuxinator(
    JsonHandlerRegistry r) async {
  await tmuxinator.loadLibrary();
  tmuxinator.registerTmuxinatorHandlers(r);
}
Future<void> _regTrex(
    JsonHandlerRegistry r) async {
  await trex.loadLibrary();
  trex.registerTrexHandlers(r);
}
Future<void> _regTrivy(
    JsonHandlerRegistry r) async {
  await trivy.loadLibrary();
  trivy.registerTrivyHandlers(r);
}
Future<void> _regTs_node(
    JsonHandlerRegistry r) async {
  await ts_node.loadLibrary();
  ts_node.registerTsNodeHandlers(r);
}
Future<void> _regTsh(
    JsonHandlerRegistry r) async {
  await tsh.loadLibrary();
  tsh.registerTshHandlers(r);
}
Future<void> _regTurbo(
    JsonHandlerRegistry r) async {
  await turbo.loadLibrary();
  turbo.registerTurboHandlers(r);
}
Future<void> _regUnset(
    JsonHandlerRegistry r) async {
  await unset.loadLibrary();
  unset.registerUnsetHandlers(r);
}
Future<void> _regV(
    JsonHandlerRegistry r) async {
  await v.loadLibrary();
  v.registerVHandlers(r);
}
Future<void> _regValet(
    JsonHandlerRegistry r) async {
  await valet.loadLibrary();
  valet.registerValetHandlers(r);
}
Future<void> _regVite(
    JsonHandlerRegistry r) async {
  await vite.loadLibrary();
  vite.registerViteHandlers(r);
}
Future<void> _regVr(
    JsonHandlerRegistry r) async {
  await vr.loadLibrary();
  vr.registerVrHandlers(r);
}
Future<void> _regVultr_cli(
    JsonHandlerRegistry r) async {
  await vultr_cli.loadLibrary();
  vultr_cli.registerVultrCliHandlers(r);
}
Future<void> _regWatson(
    JsonHandlerRegistry r) async {
  await watson.loadLibrary();
  watson.registerWatsonHandlers(r);
}
Future<void> _regWd(
    JsonHandlerRegistry r) async {
  await wd.loadLibrary();
  wd.registerWdHandlers(r);
}
Future<void> _regWhich(
    JsonHandlerRegistry r) async {
  await which.loadLibrary();
  which.registerWhichHandlers(r);
}
Future<void> _regWifi_password(
    JsonHandlerRegistry r) async {
  await wifi_password.loadLibrary();
  wifi_password.registerWifiPasswordHandlers(r);
}
Future<void> _regXc(
    JsonHandlerRegistry r) async {
  await xc.loadLibrary();
  xc.registerXcHandlers(r);
}
Future<void> _regXcodeproj(
    JsonHandlerRegistry r) async {
  await xcodeproj.loadLibrary();
  xcodeproj.registerXcodeprojHandlers(r);
}
Future<void> _regXcodes(
    JsonHandlerRegistry r) async {
  await xcodes.loadLibrary();
  xcodes.registerXcodesHandlers(r);
}
Future<void> _regYalc(
    JsonHandlerRegistry r) async {
  await yalc.loadLibrary();
  yalc.registerYalcHandlers(r);
}
Future<void> _regYarn(
    JsonHandlerRegistry r) async {
  await yarn.loadLibrary();
  yarn.registerYarnHandlers(r);
}
Future<void> _regYkman(
    JsonHandlerRegistry r) async {
  await ykman.loadLibrary();
  ykman.registerYkmanHandlers(r);
}
Future<void> _regYo(
    JsonHandlerRegistry r) async {
  await yo.loadLibrary();
  yo.registerYoHandlers(r);
}
Future<void> _regYoutube_dl(
    JsonHandlerRegistry r) async {
  await youtube_dl.loadLibrary();
  youtube_dl.registerYoutubeDlHandlers(r);
}
Future<void> _regZ(
    JsonHandlerRegistry r) async {
  await z.loadLibrary();
  z.registerZHandlers(r);
}
Future<void> _regZellij(
    JsonHandlerRegistry r) async {
  await zellij.loadLibrary();
  zellij.registerZellijHandlers(r);
}

/// Every migrated handler registrar referenced by shipped JSON, one
/// per deferred handler library.
final List<Future<void> Function(JsonHandlerRegistry)>
    allHandlerRegistrars = [
  _regAmplify,
  _regAnsible_doc,
  _regAnt,
  _regApt,
  _regArch,
  _regArduino_cli,
  _regAsdf,
  _regAssimp,
  _regAtuin,
  _regAws,
  _regAz,
  _regBat,
  _regBazel,
  _regBlack,
  _regBlitz,
  _regBosh,
  _regBrew,
  _regBun,
  _regBundle,
  _regBunx,
  _regCapacitor,
  _regCargo,
  _regCf,
  _regCheckov,
  _regChezmoi,
  _regChown,
  _regChsh,
  _regCloudwatch,
  _regComposer,
  _regConda,
  _regCopilot,
  _regCordova,
  _regDapr,
  _regDcli,
  _regDd,
  _regDefaultbrowser,
  _regDefaults,
  _regDegit,
  _regDeployctl,
  _regDjango_admin,
  _regDocker,
  _regDocker_compose,
  _regDoppler,
  _regDotnet_dynamic,
  _regDotnet_run,
  _regDotnet_tool,
  _regDrush,
  _regEb,
  _regEcho,
  _regEcs,
  _regElm,
  _regElm_json,
  _regEnv,
  _regEnvchain,
  _regEsbuild,
  _regEslint,
  _regExpressots,
  _regFfmpeg,
  _regFig,
  _regFin,
  _regFirebase,
  _regFirefox,
  _regFisher,
  _regFlyctl,
  _regFnm,
  _regFvm,
  _regGem,
  _regGh,
  _regGit,
  _regGit_cliff,
  _regGit_flow,
  _regGit_profile,
  _regGo_task,
  _regGoto,
  _regGource,
  _regGpg,
  _regHerd,
  _regHeroku,
  _regHugo,
  _regHyper,
  _regIam,
  _regIbus,
  _regIconv,
  _regId,
  _regIgnite_cli,
  _regIpatool,
  _regJ,
  _regJenv,
  _regJust,
  _regK3d,
  _regK9s,
  _regKamal,
  _regKeytool,
  _regKill,
  _regKillall,
  _regKind,
  _regKitty,
  _regKool,
  _regKubectl,
  _regKubectx,
  _regKubens,
  _regLaunchctl,
  _regLerna,
  _regLimactl,
  _regLogin,
  _regLsof,
  _regM,
  _regMackup,
  _regMagento,
  _regMake,
  _regMamba,
  _regMan,
  _regMask,
  _regMdfind,
  _regMeteor,
  _regMgnl,
  _regMix,
  _regMkinitcpio,
  _regMount,
  _regN,
  _regNetwork_quality,
  _regNetworksetup,
  _regNextflow,
  _regNg,
  _regNode,
  _regNpm,
  _regNpx,
  _regNs,
  _regNuxi,
  _regNx,
  _regOkteto,
  _regOllama,
  _regOp,
  _regOxlint,
  _regPass,
  _regPasswd,
  _regPhp,
  _regPhp_artisan,
  _regPhp_bin_console,
  _regPhp_please,
  _regPhpunit_watcher,
  _regPip,
  _regPipx,
  _regPnpm,
  _regPodman,
  _regPre_commit,
  _regProjj,
  _regPulumi,
  _regPyenv,
  _regPython,
  _regPython3,
  _regQ,
  _regQuickmail,
  _regRails,
  _regRake,
  _regRancher,
  _regRclone,
  _regReact_native,
  _regRedwood,
  _regRich,
  _regRobot,
  _regRsync,
  _regRubocop,
  _regRuff,
  _regRugby,
  _regRush,
  _regRustup,
  _regS3api,
  _regSake,
  _regScarb,
  _regScc,
  _regSecretsmanager,
  _regSequelize,
  _regServerless,
  _regShadcn_ui,
  _regShortcuts,
  _regSnaplet,
  _regSoftwareupdate,
  _regSpring,
  _regSsh,
  _regSsh_keygen,
  _regStepzen,
  _regSysctl,
  _regSystemctl,
  _regTask,
  _regTaskwarrior,
  _regTerraform,
  _regTerragrunt,
  _regTfsec,
  _regTldr,
  _regTmuxinator,
  _regTrex,
  _regTrivy,
  _regTs_node,
  _regTsh,
  _regTurbo,
  _regUnset,
  _regV,
  _regValet,
  _regVite,
  _regVr,
  _regVultr_cli,
  _regWatson,
  _regWd,
  _regWhich,
  _regWifi_password,
  _regXc,
  _regXcodeproj,
  _regXcodes,
  _regYalc,
  _regYarn,
  _regYkman,
  _regYo,
  _regYoutube_dl,
  _regZ,
  _regZellij,
];

/// Command name (as in index.json) -> the registers owning that
/// command's handlers. A command may own handlers in several files;
/// every registrar runs. Safe to call repeatedly (loadLibrary is
/// idempotent).
final Map<String, List<Future<void> Function(JsonHandlerRegistry)>>
    commandHandlerRegistrars = {
  'amplify': [_regAmplify],
  'ansible-doc': [_regAnsible_doc],
  'ant': [_regAnt],
  'apt': [_regApt],
  'arch': [_regArch],
  'arduino-cli': [_regArduino_cli],
  'artisan': [_regPhp_artisan],
  'asdf': [_regAsdf],
  'assimp': [_regAssimp],
  'atuin': [_regAtuin],
  'aws': [_regAws],
  'aws/cloudwatch': [_regCloudwatch],
  'aws/ecs': [_regEcs],
  'aws/iam': [_regIam],
  'aws/s3api': [_regS3api],
  'aws/secretsmanager': [_regSecretsmanager],
  'az': [_regAz],
  'az/2.53.0/login': [_regLogin],
  'bat': [_regBat],
  'bazel': [_regBazel],
  'bin-console': [_regPhp_bin_console],
  'black': [_regBlack],
  'blitz': [_regBlitz],
  'bosh': [_regBosh],
  'brew': [_regBrew],
  'bun': [_regBun],
  'bundle': [_regBundle],
  'bunx': [_regBunx],
  'capacitor': [_regCapacitor],
  'cargo': [_regCargo],
  'cf': [_regCf],
  'checkov': [_regCheckov],
  'chezmoi': [_regChezmoi],
  'chown': [_regChown],
  'chsh': [_regChsh],
  'cloudwatch': [_regCloudwatch],
  'composer': [_regComposer],
  'conda': [_regConda],
  'copilot': [_regCopilot],
  'cordova': [_regCordova],
  'dapr': [_regDapr],
  'dcli': [_regDcli],
  'dd': [_regDd],
  'defaultbrowser': [_regDefaultbrowser],
  'defaults': [_regDefaults],
  'degit': [_regDegit],
  'deployctl': [_regDeployctl],
  'django-admin': [_regDjango_admin],
  'docker': [_regDocker],
  'docker-compose': [_regDocker_compose],
  'doppler': [_regDoppler],
  'dotnet/dotnet-add': [_regDotnet_dynamic],
  'dotnet/dotnet-new': [_regDotnet_dynamic],
  'dotnet/dotnet-run': [_regDotnet_run],
  'dotnet/dotnet-tool': [_regDotnet_dynamic, _regDotnet_tool],
  'drush': [_regDrush],
  'eb': [_regEb],
  'echo': [_regEcho],
  'ecs': [_regEcs],
  'elm': [_regElm],
  'elm-json': [_regElm_json],
  'env': [_regEnv],
  'envchain': [_regEnvchain],
  'esbuild': [_regEsbuild],
  'eslint': [_regEslint],
  'expressots': [_regExpressots],
  'ffmpeg': [_regFfmpeg],
  'fig': [_regFig],
  'fig/1.0.0': [_regFig],
  'fig/2.0.0': [_regFig],
  'fin': [_regFin],
  'firebase': [_regFirebase],
  'firefox': [_regFirefox],
  'fisher': [_regFisher],
  'flyctl': [_regFlyctl],
  'fnm': [_regFnm],
  'fvm': [_regFvm],
  'gcloud/scc': [_regScc],
  'gem': [_regGem],
  'gh': [_regGh],
  'git': [_regGit],
  'git-cliff': [_regGit_cliff],
  'git-flow': [_regGit_flow],
  'git-profile': [_regGit_profile],
  'go-task': [_regGo_task],
  'goto': [_regGoto],
  'gource': [_regGource],
  'gpg': [_regGpg],
  'herd': [_regHerd],
  'heroku': [_regHeroku],
  'heroku/8.0.0': [_regHeroku],
  'heroku/8.6.0': [_regHeroku],
  'hugo': [_regHugo],
  'hyper': [_regHyper],
  'iam': [_regIam],
  'ibus': [_regIbus],
  'iconv': [_regIconv],
  'id': [_regId],
  'ignite-cli': [_regIgnite_cli],
  'ipatool': [_regIpatool],
  'j': [_regJ],
  'jenv': [_regJenv],
  'just': [_regJust],
  'k3d': [_regK3d],
  'k9s': [_regK9s],
  'kamal': [_regKamal],
  'keytool': [_regKeytool],
  'kill': [_regKill],
  'killall': [_regKillall],
  'kind': [_regKind],
  'kitty': [_regKitty],
  'kool': [_regKool],
  'kubectl': [_regKubectl],
  'kubectx': [_regKubectx],
  'kubens': [_regKubens],
  'launchctl': [_regLaunchctl],
  'lerna': [_regLerna],
  'limactl': [_regLimactl],
  'login': [_regLogin],
  'lsof': [_regLsof],
  'm': [_regM],
  'mackup': [_regMackup],
  'magento': [_regMagento],
  'make': [_regMake],
  'mamba': [_regMamba],
  'man': [_regMan],
  'mask': [_regMask],
  'mdfind': [_regMdfind],
  'meteor': [_regMeteor],
  'mgnl': [_regMgnl],
  'mix': [_regMix],
  'mkinitcpio': [_regMkinitcpio],
  'mount': [_regMount],
  'n': [_regN],
  'networkQuality': [_regNetwork_quality],
  'networksetup': [_regNetworksetup],
  'nextflow': [_regNextflow],
  'ng': [_regNg],
  'node': [_regNode],
  'npm': [_regNpm],
  'npx': [_regNpx],
  'ns': [_regNs],
  'nuxi': [_regNuxi],
  'nx': [_regNx],
  'okteto': [_regOkteto],
  'ollama': [_regOllama],
  'op': [_regOp],
  'oxlint': [_regOxlint],
  'pass': [_regPass],
  'passwd': [_regPasswd],
  'php': [_regPhp],
  'phpunit-watcher': [_regPhpunit_watcher],
  'pip': [_regPip],
  'pipx': [_regPipx],
  'please': [_regPhp_please],
  'pnpm': [_regPnpm],
  'podman': [_regPodman],
  'pre-commit': [_regPre_commit],
  'projj': [_regProjj],
  'pulumi': [_regPulumi],
  'pyenv': [_regPyenv],
  'python': [_regPython],
  'python3': [_regPython3],
  'q': [_regQ],
  'quickmail': [_regQuickmail],
  'rails': [_regRails],
  'rake': [_regRake],
  'rancher': [_regRancher],
  'rclone': [_regRclone],
  'react-native': [_regReact_native],
  'redwood': [_regRedwood],
  'rich': [_regRich],
  'robot': [_regRobot],
  'rsync': [_regRsync],
  'rubocop': [_regRubocop],
  'ruff': [_regRuff],
  'rugby': [_regRugby],
  'rush': [_regRush],
  'rustup': [_regRustup],
  's3api': [_regS3api],
  'sake': [_regSake],
  'scarb': [_regScarb],
  'scc': [_regScc],
  'secretsmanager': [_regSecretsmanager],
  'sequelize': [_regSequelize],
  'serverless': [_regServerless],
  'shadcn-ui': [_regShadcn_ui],
  'shortcuts': [_regShortcuts],
  'snaplet': [_regSnaplet],
  'softwareupdate': [_regSoftwareupdate],
  'ssh-keygen': [_regSsh_keygen],
  'StepZen': [_regStepzen],
  'sysctl': [_regSysctl],
  'systemctl': [_regSystemctl],
  'task': [_regTask],
  'taskwarrior': [_regTaskwarrior],
  'terraform': [_regTerraform],
  'terragrunt': [_regTerragrunt],
  'tfsec': [_regTfsec],
  'tldr': [_regTldr],
  'tmuxinator': [_regTmuxinator],
  'tool': [_regDotnet_dynamic, _regDotnet_tool],
  'trex': [_regTrex],
  'trivy': [_regTrivy],
  'ts-node': [_regTs_node],
  'tsh': [_regTsh],
  'turbo': [_regTurbo],
  'unset': [_regUnset],
  'v': [_regV],
  'valet': [_regValet],
  'vite': [_regVite],
  'vr': [_regVr],
  'vultr-cli': [_regVultr_cli],
  'watson': [_regWatson],
  'wd': [_regWd],
  'which': [_regWhich],
  'wifi-password': [_regWifi_password],
  'xc': [_regXc],
  'xcodeproj': [_regXcodeproj],
  'xcodes': [_regXcodes],
  'yalc': [_regYalc],
  'yarn': [_regYarn],
  'ykman': [_regYkman],
  'yo': [_regYo],
  'youtube-dl': [_regYoutube_dl],
  'z': [_regZ],
  'zellij': [_regZellij],
};

/// Register the handlers for [command] on demand (no-op if unknown).
Future<void> registerCommandHandlers(
    JsonHandlerRegistry registry, String command) async {
  final registrars = commandHandlerRegistrars[command];
  if (registrars == null) return;
  for (final registrar in registrars) {
    await registrar(registry);
  }
}

/// Register every migrated handler, loading each deferred library.
Future<void> registerMigratedJsonHandlers(
    JsonHandlerRegistry registry) async {
  for (final registrar in allHandlerRegistrars) {
    await registrar(registry);
  }
}
