// Hand-written dynamic handlers migrated from src/aws/iam.ts.

import 'package:autocomplete/src/json_spec.dart';
import 'package:autocomplete/src/spec.dart';

const iamCreateRoleMaxSessionDurationHandler =
    'manual.src_aws_iam.spec.subcommands_15_.options_4_.args.suggestions';
const iamGetServiceLastAccessedDetailsWithEntitiesServiceNamespaceHandler =
    'manual.src_aws_iam.spec.subcommands_78_.options_1_.args.suggestions';
const iamListPoliciesGrantingServiceAccessServiceNamespacesHandler =
    'manual.src_aws_iam.spec.subcommands_100_.options_2_.args.suggestions';
const iamUpdateRoleMaxSessionDurationHandler =
    'manual.src_aws_iam.spec.subcommands_153_.options_2_.args.suggestions';

/// The `awsPrincipals` service-principal list from the top of `src/aws/iam.ts`
/// (mirrored verbatim, including the `codedeploy.${AWS::Region}` template).
const List<String> _awsPrincipals = [
  'a4b.amazonaws.com',
  'acm-pca.amazonaws.com',
  'acm.amazonaws.com',
  'alexa-appkit.amazon.com',
  'alexa-connectedhome.amazon.com',
  'amazonmq.amazonaws.com',
  'apigateway.amazonaws.com',
  'appflow.amazonaws.com',
  'application-autoscaling.amazonaws.com',
  'appstream.application-autoscaling.amazonaws.com',
  'appsync.amazonaws.com',
  'athena.amazonaws.com',
  'autoscaling.amazonaws.com',
  'aws-artifact-account-sync.amazonaws.com',
  'backup.amazonaws.com',
  'batch.amazonaws.com',
  'billingconsole.amazonaws.com',
  'budgets.amazonaws.com',
  'ce.amazonaws.com',
  'channels.lex.amazonaws.com',
  'chime.amazonaws.com',
  'cloud9.amazonaws.com',
  'clouddirectory.amazonaws.com',
  'cloudformation.amazonaws.com',
  'cloudfront.amazonaws.com',
  'cloudhsm.amazonaws.com',
  'cloudsearch.amazonaws.com',
  'cloudtrail.amazonaws.com',
  'cloudwatch-crossaccount.amazonaws.com',
  'codebuild.amazonaws.com',
  'codecommit.amazonaws.com',
  r'codedeploy.${AWS::Region}.amazonaws.com',
  'codedeploy.amazonaws.com',
  'codepipeline.amazonaws.com',
  'codestar.amazonaws.com',
  'cognito-identity.amazonaws.com',
  'cognito-idp.amazonaws.com',
  'cognito-sync.amazonaws.com',
  'config-conforms.amazonaws.com',
  'config-multiaccountsetup.amazonaws.com',
  'config.amazonaws.com',
  'connect.amazonaws.com',
  'continuousexport.discovery.amazonaws.com',
  'custom-resource.application-autoscaling.amazonaws.com',
  'databrew.amazonaws.com',
  'datapipeline.amazonaws.com',
  'dax.amazonaws.com',
  'deeplens.amazonaws.com',
  'delivery.logs.amazonaws.com',
  'diode.amazonaws.com',
  'directconnect.amazonaws.com',
  'discovery.amazonaws.com',
  'dlm.amazonaws.com',
  'dms.amazonaws.com',
  'ds.amazonaws.com',
  'dynamodb.amazonaws.com',
  'dynamodb.application-autoscaling.amazonaws.com',
  'ec.amazonaws.com',
  'ec2.amazonaws.com',
  'ec2.application-autoscaling.amazonaws.com',
  'ec2fleet.amazonaws.com',
  'ec2scheduled.amazonaws.com',
  'ecr.amazonaws.com',
  'ecs-tasks.amazonaws.com',
  'ecs.amazonaws.com',
  'ecs.application-autoscaling.amazonaws.com',
  'edgelambda.amazonaws.com',
  'eks.amazonaws.com',
  'elasticache.amazonaws.com',
  'elasticbeanstalk.amazonaws.com',
  'elasticfilesystem.amazonaws.com',
  'elasticloadbalancing.amazonaws.com',
  'elasticmapreduce.amazonaws.com',
  'elastictranscoder.amazonaws.com',
  'email.cognito-idp.amazonaws.com',
  'es.amazonaws.com',
  'events.amazonaws.com',
  'firehose.amazonaws.com',
  'fms.amazonaws.com',
  'freertos.amazonaws.com',
  'fsx.amazonaws.com',
  'gamelift.amazonaws.com',
  'glacier.amazonaws.com',
  'globalaccelerator.amazonaws.com',
  'glue.amazonaws.com',
  'greengrass.amazonaws.com',
  'guardduty.amazonaws.com',
  'health.amazonaws.com',
  'iam.amazonaws.com',
  'importexport.amazonaws.com',
  'inspector.amazonaws.com',
  'iot.amazonaws.com',
  'iotanalytics.amazonaws.com',
  'iotevents.amazonaws.com',
  'iotsitewise.amazonaws.com',
  'iotthingsgraph.amazonaws.com',
  'jellyfish.amazonaws.com',
  'kafka.amazonaws.com',
  'kinesis.amazonaws.com',
  'kinesisanalytics.amazonaws.com',
  'kms.amazonaws.com',
  'lakeformation.amazonaws.com',
  'lambda.amazonaws.com',
  'lex.amazonaws.com',
  'license-manager.amazonaws.com',
  'lightsail.amazonaws.com',
  'logger.cloudfront.amazonaws.com',
  'logs.amazonaws.com',
  'machinelearning.amazonaws.com',
  'macie.amazonaws.com',
  'managedservices.amazonaws.com',
  'mediaconnect.amazonaws.com',
  'mediaconvert.amazonaws.com',
  'mediapackage.amazonaws.com',
  'mediastore.amazonaws.com',
  'mediatailor.amazonaws.com',
  'member.org.stacksets.cloudformation.amazonaws.com',
  'metering-marketplace.amazonaws.com',
  'migrationhub.amazonaws.com',
  'mobilehub.amazonaws.com',
  'monitoring.amazonaws.com',
  'monitoring.rds.amazonaws.com',
  'ops.apigateway.amazonaws.com',
  'opsworks-cm.amazonaws.com',
  'opsworks.amazonaws.com',
  'organizations.amazonaws.com',
  'pinpoint.amazonaws.com',
  'polly.amazonaws.com',
  'qldb.amazonaws.com',
  'quicksight.amazonaws.com',
  'ram.amazonaws.com',
  'rds.amazonaws.com',
  'redshift.amazonaws.com',
  'rekognition.amazonaws.com',
  'replication.dynamodb.amazonaws.com',
  'replicator.lambda.amazonaws.com',
  'resource-groups.amazonaws.com',
  'robomaker.amazonaws.com',
  'route53.amazonaws.com',
  'route53domains.amazonaws.com',
  'route53resolver.amazonaws.com',
  's3.amazonaws.com',
  'sagemaker.amazonaws.com',
  'secretsmanager.amazonaws.com',
  'securityhub.amazonaws.com',
  'serverlessrepo.amazonaws.com',
  'servicecatalog.amazonaws.com',
  'servicediscovery.amazonaws.com',
  'ses.amazonaws.com',
  'shield.amazonaws.com',
  'signer.amazonaws.com',
  'signin.amazonaws.com',
  'sms.amazonaws.com',
  'sns.amazonaws.com',
  'spotfleet.amazonaws.com',
  'sqs.amazonaws.com',
  'ssm.amazonaws.com',
  'sso.amazonaws.com',
  'states.amazonaws.com',
  'storagegateway.amazonaws.com',
  'sts.amazonaws.com',
  'support.amazonaws.com',
  'swf.amazonaws.com',
  'tagging.amazonaws.com',
  'tagpolicies.tag.amazonaws.com',
  'transcribe.amazonaws.com',
  'transfer.amazonaws.com',
  'translate.amazonaws.com',
  'trustedadvisor.amazonaws.com',
  'tts.amazonaws.com',
  'vmie.amazonaws.com',
  'waf-regional.amazonaws.com',
  'waf.amazonaws.com',
  'workdocs.amazonaws.com',
  'worklink.amazonaws.com',
  'workmail.amazonaws.com',
  'workspaces.amazonaws.com',
  'xray.amazonaws.com',
];

/// `--max-session-duration` values 1..12, mirroring
/// `Array.from({ length: 13 - 1 }, (_, k) => String(k + 1))`.
List<FigSuggestion> _sessionDurations() {
  return List.generate(12, (index) => FigSuggestion(name: '${index + 1}'));
}

/// Service-namespace prefixes, mirroring
/// `awsPrincipals.map((elm) => elm.slice(0, elm.indexOf('.')))`.
/// Duplicate prefixes are preserved, matching the source mapping.
List<FigSuggestion> _serviceNamespaces() {
  return _awsPrincipals
      .map((elm) => FigSuggestion(name: elm.substring(0, elm.indexOf('.'))))
      .toList();
}

/// Registers the iam suggestions handlers referenced by the shipped iam JSON.
void registerIamHandlers(JsonHandlerRegistry registry) {
  registry.registerCustom(iamCreateRoleMaxSessionDurationHandler,
      (tokens, executeCommand, context) async => _sessionDurations());
  registry.registerCustom(
      iamGetServiceLastAccessedDetailsWithEntitiesServiceNamespaceHandler,
      (tokens, executeCommand, context) async => _serviceNamespaces());
  registry.registerCustom(
      iamListPoliciesGrantingServiceAccessServiceNamespacesHandler,
      (tokens, executeCommand, context) async => _serviceNamespaces());
  registry.registerCustom(iamUpdateRoleMaxSessionDurationHandler,
      (tokens, executeCommand, context) async => _sessionDurations());
}
